<?php

namespace Database\Seeders;

use App\Models\Country;
use App\Models\Continent;
use Illuminate\Support\Str;
use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $now = getDateTime();

        // Récupérer les IDs des continents
        $asie = Continent::where('code', 'AS')->first()->id;
        $europe = Continent::where('code', 'EU')->first()->id;
        $afrique = Continent::where('code', 'AF')->first()->id;
        $ameriqueDuNord = Continent::where('code', 'NA')->first()->id;
        $ameriqueDuSud = Continent::where('code', 'SA')->first()->id;
        $oceanie = Continent::where('code', 'OC')->first()->id;
        $antarctique = Continent::where('code', 'AN')->first()->id;

        $countries = [
            [
                'name' => 'Afghanistan',
                'code' => 'AFG',
                'code_2' => 'AF',
                'phone_code' => '+93',
                'continent_id' => $asie,
            ],
            [
                'name' => 'Albanie',
                'code' => 'ALB',
                'code_2' => 'AL',
                'phone_code' => '+355',
                'continent_id' => $europe,
            ],
            [
                'name' => 'Algérie',
                'code' => 'DZA',
                'code_2' => 'DZ',
                'phone_code' => '+213',
                'continent_id' => $afrique,
            ],
            [
                'name' => 'Allemagne',
                'code' => 'DEU',
                'code_2' => 'DE',
                'phone_code' => '+49',
                'continent_id' => $europe,
            ],
            [
                'name' => 'Andorre',
                'code' => 'AND',
                'code_2' => 'AD',
                'phone_code' => '+376',
                'continent_id' => $europe,
            ],
            [
                'name' => 'Angola',
                'code' => 'AGO',
                'code_2' => 'AO',
                'phone_code' => '+244',
                'continent_id' => $afrique,
            ],
            [
                'name' => 'Antigua-et-Barbuda',
                'code' => 'ATG',
                'code_2' => 'AG',
                'phone_code' => '+1268',
                'continent_id' => $ameriqueDuNord,
            ],
            [
                'name' => 'Arabie Saoudite',
                'code' => 'SAU',
                'code_2' => 'SA',
                'phone_code' => '+966',
                'continent_id' => $asie,
            ],
            [
                'name' => 'Argentine',
                'code' => 'ARG',
                'code_2' => 'AR',
                'phone_code' => '+54',
                'continent_id' => $ameriqueDuSud,
            ],
            [
                'name' => 'Arménie',
                'code' => 'ARM',
                'code_2' => 'AM',
                'phone_code' => '+374',
                'continent_id' => $asie,
            ],
            [
                'name' => 'Australie',
                'code' => 'AUS',
                'code_2' => 'AU',
                'phone_code' => '+61',
                'continent_id' => $oceanie,
            ],
            [
                'name' => 'Autriche',
                'code' => 'AUT',
                'code_2' => 'AT',
                'phone_code' => '+43',
                'continent_id' => $europe,
            ],
            [
                'name' => 'Azerbaïdjan',
                'code' => 'AZE',
                'code_2' => 'AZ',
                'phone_code' => '+994',
                'continent_id' => $asie,
            ],
            [
                'name' => 'Bahamas',
                'code' => 'BHS',
                'code_2' => 'BS',
                'phone_code' => '+1242',
                'continent_id' => $ameriqueDuNord,
            ],
            [
                'name' => 'Bahreïn',
                'code' => 'BHR',
                'code_2' => 'BH',
                'phone_code' => '+973',
                'continent_id' => $asie,
            ],
            [
                'name' => 'Bangladesh',
                'code' => 'BGD',
                'code_2' => 'BD',
                'phone_code' => '+880',
                'continent_id' => $asie,
            ],
            [
                'name' => 'Barbade',
                'code' => 'BRB',
                'code_2' => 'BB',
                'phone_code' => '+1246',
                'continent_id' => $ameriqueDuNord,
            ],
            [
                'name' => 'Bélarus',
                'code' => 'BLR',
                'code_2' => 'BY',
                'phone_code' => '+375',
                'continent_id' => $europe,
            ],
            [
                'name' => 'Belgique',
                'code' => 'BEL',
                'code_2' => 'BE',
                'phone_code' => '+32',
                'continent_id' => $europe,
            ],
            [
                'name' => 'Belize',
                'code' => 'BLZ',
                'code_2' => 'BZ',
                'phone_code' => '+501',
                'continent_id' => $ameriqueDuNord,
            ],
            [
                'name' => 'Bénin',
                'code' => 'BEN',
                'code_2' => 'BJ',
                'phone_code' => '+229',
                'continent_id' => $afrique,
            ],
            [
                'name' => 'Bhoutan',
                'code' => 'BTN',
                'code_2' => 'BT',
                'phone_code' => '+975',
                'continent_id' => $asie,
            ],
            [
                'name' => 'Bolivie',
                'code' => 'BOL',
                'code_2' => 'BO',
                'phone_code' => '+591',
                'continent_id' => $ameriqueDuSud,
            ],
            [
                'name' => 'Bosnie-Herzégovine',
                'code' => 'BIH',
                'code_2' => 'BA',
                'phone_code' => '+387',
                'continent_id' => $europe,
            ],
            [
                'name' => 'Botswana',
                'code' => 'BWA',
                'code_2' => 'BW',
                'phone_code' => '+267',
                'continent_id' => $afrique,
            ],
            [
                'name' => 'Brésil',
                'code' => 'BRA',
                'code_2' => 'BR',
                'phone_code' => '+55',
                'continent_id' => $ameriqueDuSud,
            ],
            [
                'name' => 'Brunei',
                'code' => 'BRN',
                'code_2' => 'BN',
                'phone_code' => '+673',
                'continent_id' => $asie,
            ],
            [
                'name' => 'Bulgarie',
                'code' => 'BGR',
                'code_2' => 'BG',
                'phone_code' => '+359',
                'continent_id' => $europe,
            ],
            [
                'name' => 'Burkina Faso',
                'code' => 'BFA',
                'code_2' => 'BF',
                'phone_code' => '+226',
                'continent_id' => $afrique,
            ],
            [
                'name' => 'Burundi',
                'code' => 'BDI',
                'code_2' => 'BI',
                'phone_code' => '+257',
                'continent_id' => $afrique,
            ],
            // 
            // 
            // 
            // 
            // 
            // 
            // 
            // 
            // 
            // 
            [
                'name' => 'Cambodge',
                'code' => 'KHM',
                'code_2' => 'KH',
                'phone_code' => '+855',
                'continent_id' => $asie,
            ],
            [
                'name' => 'Cameroun',
                'code' => 'CMR',
                'code_2' => 'CM',
                'phone_code' => '+237',
                'continent_id' => $afrique,
            ],
            [
                'name' => 'Canada',
                'code' => 'CAN',
                'code_2' => 'CA',
                'phone_code' => '+1',
                'continent_id' => $ameriqueDuNord,
            ],
            [
                'name' => 'Cap-Vert',
                'code' => 'CPV',
                'code_2' => 'CV',
                'phone_code' => '+238',
                'continent_id' => $afrique,
            ],
            [
                'name' => 'Chili',
                'code' => 'CHL',
                'code_2' => 'CL',
                'phone_code' => '+56',
                'continent_id' => $ameriqueDuSud,
            ],
            [
                'name' => 'Chine',
                'code' => 'CHN',
                'code_2' => 'CN',
                'phone_code' => '+86',
                'continent_id' => $asie,
            ],
            [
                'name' => 'Chypre',
                'code' => 'CYP',
                'code_2' => 'CY',
                'phone_code' => '+357',
                'continent_id' => $europe,
            ],
            [
                'name' => 'Colombie',
                'code' => 'COL',
                'code_2' => 'CO',
                'phone_code' => '+57',
                'continent_id' => $ameriqueDuSud,
            ],
            [
                'name' => 'Comores',
                'code' => 'COM',
                'code_2' => 'KM',
                'phone_code' => '+269',
                'continent_id' => $afrique,
            ],
            [
                'name' => 'Congo',
                'code' => 'COG',
                'code_2' => 'CG',
                'phone_code' => '+242',
                'continent_id' => $afrique,
            ],
            [
                'name' => 'Congo (République démocratique)',
                'code' => 'COD',
                'code_2' => 'CD',
                'phone_code' => '+243',
                'continent_id' => $afrique,
            ],
            [
                'name' => 'Corée du Nord',
                'code' => 'PRK',
                'code_2' => 'KP',
                'phone_code' => '+850',
                'continent_id' => $asie,
            ],
            [
                'name' => 'Corée du Sud',
                'code' => 'KOR',
                'code_2' => 'KR',
                'phone_code' => '+82',
                'continent_id' => $asie,
            ],
            [
                'name' => 'Costa Rica',
                'code' => 'CRI',
                'code_2' => 'CR',
                'phone_code' => '+506',
                'continent_id' => $ameriqueDuNord,
            ],
            [
                'name' => 'Côte d\'Ivoire',
                'code' => 'CIV',
                'code_2' => 'CI',
                'phone_code' => '+225',
                'continent_id' => $afrique,
            ],
            [
                'name' => 'Croatie',
                'code' => 'HRV',
                'code_2' => 'HR',
                'phone_code' => '+385',
                'continent_id' => $europe,
            ],
            [
                'name' => 'Cuba',
                'code' => 'CUB',
                'code_2' => 'CU',
                'phone_code' => '+53',
                'continent_id' => $ameriqueDuNord,
            ],
            [
                'name' => 'Danemark',
                'code' => 'DNK',
                'code_2' => 'DK',
                'phone_code' => '+45',
                'continent_id' => $europe,
            ],
            [
                'name' => 'Djibouti',
                'code' => 'DJI',
                'code_2' => 'DJ',
                'phone_code' => '+253',
                'continent_id' => $afrique,
            ],
            [
                'name' => 'Dominique',
                'code' => 'DMA',
                'code_2' => 'DM',
                'phone_code' => '+1767',
                'continent_id' => $ameriqueDuNord,
            ],
            [
                'name' => 'Égypte',
                'code' => 'EGY',
                'code_2' => 'EG',
                'phone_code' => '+20',
                'continent_id' => $afrique,
            ],
            [
                'name' => 'Émirats arabes unis',
                'code' => 'ARE',
                'code_2' => 'AE',
                'phone_code' => '+971',
                'continent_id' => $asie,
            ],
            [
                'name' => 'Équateur',
                'code' => 'ECU',
                'code_2' => 'EC',
                'phone_code' => '+593',
                'continent_id' => $ameriqueDuSud,
            ],
            [
                'name' => 'Érythrée',
                'code' => 'ERI',
                'code_2' => 'ER',
                'phone_code' => '+291',
                'continent_id' => $afrique,
            ],
            [
                'name' => 'Espagne',
                'code' => 'ESP',
                'code_2' => 'ES',
                'phone_code' => '+34',
                'continent_id' => $europe,
            ],
            [
                'name' => 'Estonie',
                'code' => 'EST',
                'code_2' => 'EE',
                'phone_code' => '+372',
                'continent_id' => $europe,
            ],
            [
                'name' => 'Eswatini',
                'code' => 'SWZ',
                'code_2' => 'SZ',
                'phone_code' => '+268',
                'continent_id' => $afrique,
            ],
            [
                'name' => 'États-Unis',
                'code' => 'USA',
                'code_2' => 'US',
                'phone_code' => '+1',
                'continent_id' => $ameriqueDuNord,
            ],
            [
                'name' => 'Éthiopie',
                'code' => 'ETH',
                'code_2' => 'ET',
                'phone_code' => '+251',
                'continent_id' => $afrique,
            ],
            [
                'name' => 'Fidji',
                'code' => 'FJI',
                'code_2' => 'FJ',
                'phone_code' => '+679',
                'continent_id' => $oceanie,
            ],
            [
                'name' => 'Finlande',
                'code' => 'FIN',
                'code_2' => 'FI',
                'phone_code' => '+358',
                'continent_id' => $europe,
            ],
            [
                'name' => 'France',
                'code' => 'FRA',
                'code_2' => 'FR',
                'phone_code' => '+33',
                'continent_id' => $europe,
            ],
            [
                'name' => 'Gabon',
                'code' => 'GAB',
                'code_2' => 'GA',
                'phone_code' => '+241',
                'continent_id' => $afrique,
            ],
            [
                'name' => 'Gambie',
                'code' => 'GMB',
                'code_2' => 'GM',
                'phone_code' => '+220',
                'continent_id' => $afrique,
            ],
            [
                'name' => 'Géorgie',
                'code' => 'GEO',
                'code_2' => 'GE',
                'phone_code' => '+995',
                'continent_id' => $asie,
            ],
            [
                'name' => 'Ghana',
                'code' => 'GHA',
                'code_2' => 'GH',
                'phone_code' => '+233',
                'continent_id' => $afrique,
            ],
            [
                'name' => 'Grèce',
                'code' => 'GRC',
                'code_2' => 'GR',
                'phone_code' => '+30',
                'continent_id' => $europe,
            ],
            [
                'name' => 'Grenade',
                'code' => 'GRD',
                'code_2' => 'GD',
                'phone_code' => '+1473',
                'continent_id' => $ameriqueDuNord,
            ],
            [
                'name' => 'Guatemala',
                'code' => 'GTM',
                'code_2' => 'GT',
                'phone_code' => '+502',
                'continent_id' => $ameriqueDuNord,
            ],
            [
                'name' => 'Guinée',
                'code' => 'GIN',
                'code_2' => 'GN',
                'phone_code' => '+224',
                'continent_id' => $afrique,
            ],
            [
                'name' => 'Guinée-Bissau',
                'code' => 'GNB',
                'code_2' => 'GW',
                'phone_code' => '+245',
                'continent_id' => $afrique,
            ],
            [
                'name' => 'Guinée équatoriale',
                'code' => 'GNQ',
                'code_2' => 'GQ',
                'phone_code' => '+240',
                'continent_id' => $afrique,
            ],
            [
                'name' => 'Guyana',
                'code' => 'GUY',
                'code_2' => 'GY',
                'phone_code' => '+592',
                'continent_id' => $ameriqueDuSud,
            ],
            // 
            // 
            // 
            // 
            // 
            // 
            // 
            // 
            // 
            // NOUVEAUX PAYS (suite)
            [
                'name' => 'Haïti',
                'code' => 'HTI',
                'code_2' => 'HT',
                'phone_code' => '+509',
                'continent_id' => $ameriqueDuNord,
            ],
            [
                'name' => 'Honduras',
                'code' => 'HND',
                'code_2' => 'HN',
                'phone_code' => '+504',
                'continent_id' => $ameriqueDuNord,
            ],
            [
                'name' => 'Hongrie',
                'code' => 'HUN',
                'code_2' => 'HU',
                'phone_code' => '+36',
                'continent_id' => $europe,
            ],
            [
                'name' => 'Îles Cook',
                'code' => 'COK',
                'code_2' => 'CK',
                'phone_code' => '+682',
                'continent_id' => $oceanie,
            ],
            [
                'name' => 'Îles Marshall',
                'code' => 'MHL',
                'code_2' => 'MH',
                'phone_code' => '+692',
                'continent_id' => $oceanie,
            ],
            [
                'name' => 'Îles Salomon',
                'code' => 'SLB',
                'code_2' => 'SB',
                'phone_code' => '+677',
                'continent_id' => $oceanie,
            ],
            [
                'name' => 'Inde',
                'code' => 'IND',
                'code_2' => 'IN',
                'phone_code' => '+91',
                'continent_id' => $asie,
            ],
            [
                'name' => 'Indonésie',
                'code' => 'IDN',
                'code_2' => 'ID',
                'phone_code' => '+62',
                'continent_id' => $asie,
            ],
            [
                'name' => 'Irak',
                'code' => 'IRQ',
                'code_2' => 'IQ',
                'phone_code' => '+964',
                'continent_id' => $asie,
            ],
            [
                'name' => 'Iran',
                'code' => 'IRN',
                'code_2' => 'IR',
                'phone_code' => '+98',
                'continent_id' => $asie,
            ],
            [
                'name' => 'Irlande',
                'code' => 'IRL',
                'code_2' => 'IE',
                'phone_code' => '+353',
                'continent_id' => $europe,
            ],
            [
                'name' => 'Islande',
                'code' => 'ISL',
                'code_2' => 'IS',
                'phone_code' => '+354',
                'continent_id' => $europe,
            ],
            [
                'name' => 'Israël',
                'code' => 'ISR',
                'code_2' => 'IL',
                'phone_code' => '+972',
                'continent_id' => $asie,
            ],
            [
                'name' => 'Italie',
                'code' => 'ITA',
                'code_2' => 'IT',
                'phone_code' => '+39',
                'continent_id' => $europe,
            ],
            [
                'name' => 'Jamaïque',
                'code' => 'JAM',
                'code_2' => 'JM',
                'phone_code' => '+1876',
                'continent_id' => $ameriqueDuNord,
            ],
            [
                'name' => 'Japon',
                'code' => 'JPN',
                'code_2' => 'JP',
                'phone_code' => '+81',
                'continent_id' => $asie,
            ],
            [
                'name' => 'Jordanie',
                'code' => 'JOR',
                'code_2' => 'JO',
                'phone_code' => '+962',
                'continent_id' => $asie,
            ],
            [
                'name' => 'Kazakhstan',
                'code' => 'KAZ',
                'code_2' => 'KZ',
                'phone_code' => '+7',
                'continent_id' => $asie,
            ],
            [
                'name' => 'Kenya',
                'code' => 'KEN',
                'code_2' => 'KE',
                'phone_code' => '+254',
                'continent_id' => $afrique,
            ],
            [
                'name' => 'Kirghizistan',
                'code' => 'KGZ',
                'code_2' => 'KG',
                'phone_code' => '+996',
                'continent_id' => $asie,
            ],
            [
                'name' => 'Kiribati',
                'code' => 'KIR',
                'code_2' => 'KI',
                'phone_code' => '+686',
                'continent_id' => $oceanie,
            ],
            [
                'name' => 'Koweït',
                'code' => 'KWT',
                'code_2' => 'KW',
                'phone_code' => '+965',
                'continent_id' => $asie,
            ],
            [
                'name' => 'Laos',
                'code' => 'LAO',
                'code_2' => 'LA',
                'phone_code' => '+856',
                'continent_id' => $asie,
            ],
            [
                'name' => 'Lesotho',
                'code' => 'LSO',
                'code_2' => 'LS',
                'phone_code' => '+266',
                'continent_id' => $afrique,
            ],
            [
                'name' => 'Lettonie',
                'code' => 'LVA',
                'code_2' => 'LV',
                'phone_code' => '+371',
                'continent_id' => $europe,
            ],
            [
                'name' => 'Liban',
                'code' => 'LBN',
                'code_2' => 'LB',
                'phone_code' => '+961',
                'continent_id' => $asie,
            ],
            [
                'name' => 'Liberia',
                'code' => 'LBR',
                'code_2' => 'LR',
                'phone_code' => '+231',
                'continent_id' => $afrique,
            ],
            [
                'name' => 'Libye',
                'code' => 'LBY',
                'code_2' => 'LY',
                'phone_code' => '+218',
                'continent_id' => $afrique,
            ],
            [
                'name' => 'Liechtenstein',
                'code' => 'LIE',
                'code_2' => 'LI',
                'phone_code' => '+423',
                'continent_id' => $europe,
            ],
            [
                'name' => 'Lituanie',
                'code' => 'LTU',
                'code_2' => 'LT',
                'phone_code' => '+370',
                'continent_id' => $europe,
            ],
            [
                'name' => 'Luxembourg',
                'code' => 'LUX',
                'code_2' => 'LU',
                'phone_code' => '+352',
                'continent_id' => $europe,
            ],
            // 
            // 
            // 
            // 
            // 
            // 
            // 
            // 
            // 
            // NOUVEAUX PAYS (suite)
            [
                'name' => 'Macédoine du Nord',
                'code' => 'MKD',
                'code_2' => 'MK',
                'phone_code' => '+389',
                'continent_id' => $europe,
            ],
            [
                'name' => 'Madagascar',
                'code' => 'MDG',
                'code_2' => 'MG',
                'phone_code' => '+261',
                'continent_id' => $afrique,
            ],
            [
                'name' => 'Malaisie',
                'code' => 'MYS',
                'code_2' => 'MY',
                'phone_code' => '+60',
                'continent_id' => $asie,
            ],
            [
                'name' => 'Malawi',
                'code' => 'MWI',
                'code_2' => 'MW',
                'phone_code' => '+265',
                'continent_id' => $afrique,
            ],
            [
                'name' => 'Maldives',
                'code' => 'MDV',
                'code_2' => 'MV',
                'phone_code' => '+960',
                'continent_id' => $asie,
            ],
            [
                'name' => 'Mali',
                'code' => 'MLI',
                'code_2' => 'ML',
                'phone_code' => '+223',
                'continent_id' => $afrique,
            ],
            [
                'name' => 'Malte',
                'code' => 'MLT',
                'code_2' => 'MT',
                'phone_code' => '+356',
                'continent_id' => $europe,
            ],
            [
                'name' => 'Maroc',
                'code' => 'MAR',
                'code_2' => 'MA',
                'phone_code' => '+212',
                'continent_id' => $afrique,
            ],
            [
                'name' => 'Maurice',
                'code' => 'MUS',
                'code_2' => 'MU',
                'phone_code' => '+230',
                'continent_id' => $afrique,
            ],
            [
                'name' => 'Mauritanie',
                'code' => 'MRT',
                'code_2' => 'MR',
                'phone_code' => '+222',
                'continent_id' => $afrique,
            ],
            [
                'name' => 'Mexique',
                'code' => 'MEX',
                'code_2' => 'MX',
                'phone_code' => '+52',
                'continent_id' => $ameriqueDuNord,
            ],
            [
                'name' => 'Micronésie',
                'code' => 'FSM',
                'code_2' => 'FM',
                'phone_code' => '+691',
                'continent_id' => $oceanie,
            ],
            [
                'name' => 'Moldova',
                'code' => 'MDA',
                'code_2' => 'MD',
                'phone_code' => '+373',
                'continent_id' => $europe,
            ],
            [
                'name' => 'Monaco',
                'code' => 'MCO',
                'code_2' => 'MC',
                'phone_code' => '+377',
                'continent_id' => $europe,
            ],
            [
                'name' => 'Mongolie',
                'code' => 'MNG',
                'code_2' => 'MN',
                'phone_code' => '+976',
                'continent_id' => $asie,
            ],
            [
                'name' => 'Monténégro',
                'code' => 'MNE',
                'code_2' => 'ME',
                'phone_code' => '+382',
                'continent_id' => $europe,
            ],
            [
                'name' => 'Mozambique',
                'code' => 'MOZ',
                'code_2' => 'MZ',
                'phone_code' => '+258',
                'continent_id' => $afrique,
            ],
            [
                'name' => 'Myanmar',
                'code' => 'MMR',
                'code_2' => 'MM',
                'phone_code' => '+95',
                'continent_id' => $asie,
            ],
            [
                'name' => 'Namibie',
                'code' => 'NAM',
                'code_2' => 'NA',
                'phone_code' => '+264',
                'continent_id' => $afrique,
            ],
            [
                'name' => 'Nauru',
                'code' => 'NRU',
                'code_2' => 'NR',
                'phone_code' => '+674',
                'continent_id' => $oceanie,
            ],
            [
                'name' => 'Népal',
                'code' => 'NPL',
                'code_2' => 'NP',
                'phone_code' => '+977',
                'continent_id' => $asie,
            ],
            [
                'name' => 'Nicaragua',
                'code' => 'NIC',
                'code_2' => 'NI',
                'phone_code' => '+505',
                'continent_id' => $ameriqueDuNord,
            ],
            [
                'name' => 'Niger',
                'code' => 'NER',
                'code_2' => 'NE',
                'phone_code' => '+227',
                'continent_id' => $afrique,
            ],
            [
                'name' => 'Nigeria',
                'code' => 'NGA',
                'code_2' => 'NG',
                'phone_code' => '+234',
                'continent_id' => $afrique,
            ],
            [
                'name' => 'Niue',
                'code' => 'NIU',
                'code_2' => 'NU',
                'phone_code' => '+683',
                'continent_id' => $oceanie,
            ],
            [
                'name' => 'Norvège',
                'code' => 'NOR',
                'code_2' => 'NO',
                'phone_code' => '+47',
                'continent_id' => $europe,
            ],
            [
                'name' => 'Nouvelle-Zélande',
                'code' => 'NZL',
                'code_2' => 'NZ',
                'phone_code' => '+64',
                'continent_id' => $oceanie,
            ],
            [
                'name' => 'Oman',
                'code' => 'OMN',
                'code_2' => 'OM',
                'phone_code' => '+968',
                'continent_id' => $asie,
            ],
            [
                'name' => 'Ouganda',
                'code' => 'UGA',
                'code_2' => 'UG',
                'phone_code' => '+256',
                'continent_id' => $afrique,
            ],
            [
                'name' => 'Ouzbékistan',
                'code' => 'UZB',
                'code_2' => 'UZ',
                'phone_code' => '+998',
                'continent_id' => $asie,
            ],
            [
                'name' => 'Pakistan',
                'code' => 'PAK',
                'code_2' => 'PK',
                'phone_code' => '+92',
                'continent_id' => $asie,
            ],
            [
                'name' => 'Palaos',
                'code' => 'PLW',
                'code_2' => 'PW',
                'phone_code' => '+680',
                'continent_id' => $oceanie,
            ],
            [
                'name' => 'Palestine',
                'code' => 'PSE',
                'code_2' => 'PS',
                'phone_code' => '+970',
                'continent_id' => $asie,
            ],
            [
                'name' => 'Panama',
                'code' => 'PAN',
                'code_2' => 'PA',
                'phone_code' => '+507',
                'continent_id' => $ameriqueDuNord,
            ],
            [
                'name' => 'Papouasie-Nouvelle-Guinée',
                'code' => 'PNG',
                'code_2' => 'PG',
                'phone_code' => '+675',
                'continent_id' => $oceanie,
            ],
            [
                'name' => 'Paraguay',
                'code' => 'PRY',
                'code_2' => 'PY',
                'phone_code' => '+595',
                'continent_id' => $ameriqueDuSud,
            ],
            [
                'name' => 'Pays-Bas',
                'code' => 'NLD',
                'code_2' => 'NL',
                'phone_code' => '+31',
                'continent_id' => $europe,
            ],
            [
                'name' => 'Pérou',
                'code' => 'PER',
                'code_2' => 'PE',
                'phone_code' => '+51',
                'continent_id' => $ameriqueDuSud,
            ],
            [
                'name' => 'Philippines',
                'code' => 'PHL',
                'code_2' => 'PH',
                'phone_code' => '+63',
                'continent_id' => $asie,
            ],
            [
                'name' => 'Pologne',
                'code' => 'POL',
                'code_2' => 'PL',
                'phone_code' => '+48',
                'continent_id' => $europe,
            ],
            [
                'name' => 'Portugal',
                'code' => 'PRT',
                'code_2' => 'PT',
                'phone_code' => '+351',
                'continent_id' => $europe,
            ],
            // 
            // 
            // 
            // 
            // 
            // 
            // 
            // 
            // DERNIERS PAYS
            [
                'name' => 'Qatar',
                'code' => 'QAT',
                'code_2' => 'QA',
                'phone_code' => '+974',
                'continent_id' => $asie,
            ],
            [
                'name' => 'République centrafricaine',
                'code' => 'CAF',
                'code_2' => 'CF',
                'phone_code' => '+236',
                'continent_id' => $afrique,
            ],
            [
                'name' => 'République dominicaine',
                'code' => 'DOM',
                'code_2' => 'DO',
                'phone_code' => '+1809',
                'continent_id' => $ameriqueDuNord,
            ],
            [
                'name' => 'République tchèque',
                'code' => 'CZE',
                'code_2' => 'CZ',
                'phone_code' => '+420',
                'continent_id' => $europe,
            ],
            [
                'name' => 'Roumanie',
                'code' => 'ROU',
                'code_2' => 'RO',
                'phone_code' => '+40',
                'continent_id' => $europe,
            ],
            [
                'name' => 'Royaume-Uni',
                'code' => 'GBR',
                'code_2' => 'GB',
                'phone_code' => '+44',
                'continent_id' => $europe,
            ],
            [
                'name' => 'Russie',
                'code' => 'RUS',
                'code_2' => 'RU',
                'phone_code' => '+7',
                'continent_id' => $europe,
            ],
            [
                'name' => 'Rwanda',
                'code' => 'RWA',
                'code_2' => 'RW',
                'phone_code' => '+250',
                'continent_id' => $afrique,
            ],
            [
                'name' => 'Saint-Christophe-et-Niévès',
                'code' => 'KNA',
                'code_2' => 'KN',
                'phone_code' => '+1869',
                'continent_id' => $ameriqueDuNord,
            ],
            [
                'name' => 'Saint-Marin',
                'code' => 'SMR',
                'code_2' => 'SM',
                'phone_code' => '+378',
                'continent_id' => $europe,
            ],
            [
                'name' => 'Saint-Vincent-et-les-Grenadines',
                'code' => 'VCT',
                'code_2' => 'VC',
                'phone_code' => '+1784',
                'continent_id' => $ameriqueDuNord,
            ],
            [
                'name' => 'Sainte-Lucie',
                'code' => 'LCA',
                'code_2' => 'LC',
                'phone_code' => '+1758',
                'continent_id' => $ameriqueDuNord,
            ],
            [
                'name' => 'Salvador',
                'code' => 'SLV',
                'code_2' => 'SV',
                'phone_code' => '+503',
                'continent_id' => $ameriqueDuNord,
            ],
            [
                'name' => 'Samoa',
                'code' => 'WSM',
                'code_2' => 'WS',
                'phone_code' => '+685',
                'continent_id' => $oceanie,
            ],
            [
                'name' => 'São Tomé-et-Principe',
                'code' => 'STP',
                'code_2' => 'ST',
                'phone_code' => '+239',
                'continent_id' => $afrique,
            ],
            [
                'name' => 'Sénégal',
                'code' => 'SEN',
                'code_2' => 'SN',
                'phone_code' => '+221',
                'continent_id' => $afrique,
            ],
            [
                'name' => 'Serbie',
                'code' => 'SRB',
                'code_2' => 'RS',
                'phone_code' => '+381',
                'continent_id' => $europe,
            ],
            [
                'name' => 'Seychelles',
                'code' => 'SYC',
                'code_2' => 'SC',
                'phone_code' => '+248',
                'continent_id' => $afrique,
            ],
            [
                'name' => 'Sierra Leone',
                'code' => 'SLE',
                'code_2' => 'SL',
                'phone_code' => '+232',
                'continent_id' => $afrique,
            ],
            [
                'name' => 'Singapour',
                'code' => 'SGP',
                'code_2' => 'SG',
                'phone_code' => '+65',
                'continent_id' => $asie,
            ],
            [
                'name' => 'Slovaquie',
                'code' => 'SVK',
                'code_2' => 'SK',
                'phone_code' => '+421',
                'continent_id' => $europe,
            ],
            [
                'name' => 'Slovénie',
                'code' => 'SVN',
                'code_2' => 'SI',
                'phone_code' => '+386',
                'continent_id' => $europe,
            ],
            [
                'name' => 'Somalie',
                'code' => 'SOM',
                'code_2' => 'SO',
                'phone_code' => '+252',
                'continent_id' => $afrique,
            ],
            [
                'name' => 'Soudan',
                'code' => 'SDN',
                'code_2' => 'SD',
                'phone_code' => '+249',
                'continent_id' => $afrique,
            ],
            [
                'name' => 'Soudan du Sud',
                'code' => 'SSD',
                'code_2' => 'SS',
                'phone_code' => '+211',
                'continent_id' => $afrique,
            ],
            [
                'name' => 'Sri Lanka',
                'code' => 'LKA',
                'code_2' => 'LK',
                'phone_code' => '+94',
                'continent_id' => $asie,
            ],
            [
                'name' => 'Suède',
                'code' => 'SWE',
                'code_2' => 'SE',
                'phone_code' => '+46',
                'continent_id' => $europe,
            ],
            [
                'name' => 'Suisse',
                'code' => 'CHE',
                'code_2' => 'CH',
                'phone_code' => '+41',
                'continent_id' => $europe,
            ],
            [
                'name' => 'Suriname',
                'code' => 'SUR',
                'code_2' => 'SR',
                'phone_code' => '+597',
                'continent_id' => $ameriqueDuSud,
            ],
            [
                'name' => 'Syrie',
                'code' => 'SYR',
                'code_2' => 'SY',
                'phone_code' => '+963',
                'continent_id' => $asie,
            ],
            [
                'name' => 'Tadjikistan',
                'code' => 'TJK',
                'code_2' => 'TJ',
                'phone_code' => '+992',
                'continent_id' => $asie,
            ],
            [
                'name' => 'Tanzanie',
                'code' => 'TZA',
                'code_2' => 'TZ',
                'phone_code' => '+255',
                'continent_id' => $afrique,
            ],
            [
                'name' => 'Tchad',
                'code' => 'TCD',
                'code_2' => 'TD',
                'phone_code' => '+235',
                'continent_id' => $afrique,
            ],
            [
                'name' => 'Thaïlande',
                'code' => 'THA',
                'code_2' => 'TH',
                'phone_code' => '+66',
                'continent_id' => $asie,
            ],
            [
                'name' => 'Timor oriental',
                'code' => 'TLS',
                'code_2' => 'TL',
                'phone_code' => '+670',
                'continent_id' => $asie,
            ],
            [
                'name' => 'Togo',
                'code' => 'TGO',
                'code_2' => 'TG',
                'phone_code' => '+228',
                'continent_id' => $afrique,
            ],
            [
                'name' => 'Tonga',
                'code' => 'TON',
                'code_2' => 'TO',
                'phone_code' => '+676',
                'continent_id' => $oceanie,
            ],
            [
                'name' => 'Trinité-et-Tobago',
                'code' => 'TTO',
                'code_2' => 'TT',
                'phone_code' => '+1868',
                'continent_id' => $ameriqueDuNord,
            ],
            [
                'name' => 'Tunisie',
                'code' => 'TUN',
                'code_2' => 'TN',
                'phone_code' => '+216',
                'continent_id' => $afrique,
            ],
            [
                'name' => 'Turkménistan',
                'code' => 'TKM',
                'code_2' => 'TM',
                'phone_code' => '+993',
                'continent_id' => $asie,
            ],
            [
                'name' => 'Turquie',
                'code' => 'TUR',
                'code_2' => 'TR',
                'phone_code' => '+90',
                'continent_id' => $asie,
            ],
            [
                'name' => 'Tuvalu',
                'code' => 'TUV',
                'code_2' => 'TV',
                'phone_code' => '+688',
                'continent_id' => $oceanie,
            ],
            [
                'name' => 'Ukraine',
                'code' => 'UKR',
                'code_2' => 'UA',
                'phone_code' => '+380',
                'continent_id' => $europe,
            ],
            [
                'name' => 'Uruguay',
                'code' => 'URY',
                'code_2' => 'UY',
                'phone_code' => '+598',
                'continent_id' => $ameriqueDuSud,
            ],
            [
                'name' => 'Vanuatu',
                'code' => 'VUT',
                'code_2' => 'VU',
                'phone_code' => '+678',
                'continent_id' => $oceanie,
            ],
            [
                'name' => 'Vatican',
                'code' => 'VAT',
                'code_2' => 'VA',
                'phone_code' => '+379',
                'continent_id' => $europe,
            ],
            [
                'name' => 'Venezuela',
                'code' => 'VEN',
                'code_2' => 'VE',
                'phone_code' => '+58',
                'continent_id' => $ameriqueDuSud,
            ],
            [
                'name' => 'Vietnam',
                'code' => 'VNM',
                'code_2' => 'VN',
                'phone_code' => '+84',
                'continent_id' => $asie,
            ],
            [
                'name' => 'Yémen',
                'code' => 'YEM',
                'code_2' => 'YE',
                'phone_code' => '+967',
                'continent_id' => $asie,
            ],
            [
                'name' => 'Zambie',
                'code' => 'ZMB',
                'code_2' => 'ZM',
                'phone_code' => '+260',
                'continent_id' => $afrique,
            ],
            [
                'name' => 'Zimbabwe',
                'code' => 'ZWE',
                'code_2' => 'ZW',
                'phone_code' => '+263',
                'continent_id' => $afrique,
            ],
        ];

        foreach ($countries as $country) {

            $token = Str::random(10);
            while(Country::where('token', $token)->exists()) {
                $token = Str::random(10);
            }

            Country::create([
                'name' => $country['name'],
                'code' => $country['code'],
                'code_2' => $country['code_2'],
                'phone_code' => $country['phone_code'],
                'token' => $token,
                'continent_id' => $country['continent_id'],
                'is_active' => true,
                'path_img' => 'others/all/countries/images/default.png',
                'created_at' => $now,
                'updated_at' => $now,
            ]);
        }
    }
}